using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Euler
{
    /**
     * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
     * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
     * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
     */
    public class Problem2
    {
        public int solve()
        {
            int newResult = 1;
            int oldResult = 0;
            int evenSum = 0;
            while (newResult < 4_000_000)
            {
                var temp = newResult;
                newResult = oldResult + newResult;
                oldResult = temp;
                if (newResult % 2 == 0)
                    evenSum += newResult;
            }
            return evenSum;
        }
    }
}
